version: '3'

services:
  dev-c-asm:
    build: .
    platform: linux/amd64
    container_name: dev-c-asm
    volumes:
      - ./src:/app/src
    working_dir: /app
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 2G
